# Change these first
owner: miners-online # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

skipDeleteIssues: true

sites:
  - name: Miners Online website
    url: https://minersonline.uk
  - name: Minecraft server
    url: local.minersonline.uk
    port: 25565
    check: "tcp-ping"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.minersonline.uk
  # baseUrl: /your-repo-name
  logoUrl: https://github.com/miners-online/status/raw/master/assets/favicon.svg
  faviconSvg: https://github.com/miners-online/status/raw/master/assets/favicon.svg
  name: Miners Online status
  introTitle: "Status page for Miners Online"
  introMessage: View the status of all Miners Online services using our GitHub and [Upptime](https://github.com/upptime/upptime) powered status page.
  navbar:
    - title: Miners Online Home
      href: https://minersonline.uk
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
